<?php /* Smarty version 2.6.0, created on 2009-12-12 14:06:04
         compiled from blank.tpl */ ?>
<div align="center"><h1><?php echo $this->_tpl_vars['maintitle']; ?>
</h1></div>
<b>Welcome to <?php echo $this->_tpl_vars['package']; ?>
!</b><br />
<br />
This documentation was generated by <a href="<?php echo $this->_tpl_vars['phpdocwebsite']; ?>
">phpDocumentor v<?php echo $this->_tpl_vars['phpdocversion']; ?>
</a><br />
