<?php
	$name = $selenium->randomString(10);
	$name2 = $selenium->randomString(10);
	$name3 = $selenium->randomString(10);
	$password = $selenium->randomString(10);
	$password2 = $selenium->randomString(10);	
	$password3 = $selenium->randomString(10);		
	$message = $selenium->randomString(10);
	$message2 = $selenium->randomString(10);	
	$message3 = $selenium->randomString(10);		
	$email = "nomcat+".$selenium->randomString(10) . '@wearenom.com';	
	$email2 = "nomcat+".$selenium->randomString(10) . '@wearenom.com';		
	$email3 = "nomcat+".$selenium->randomString(10) . '@wearenom.com';			
	$count = $this->testingData['count'];
	$group = $selenium->randomString(10);
	$group2 = $selenium->randomString(10);
	$group3 = $selenium->randomString(10);
		
	$selenium->caseTitle('Direct Message Select Form');	
	$selenium->signOut();
	$selenium->write('verifyValue', 'testing_count', $count);	
	//sign up three accounts
	$selenium->signUp($name, $password, $email);
	$selenium->write('verifyValue', 'testing_count', $count + 4);	
	$selenium->signOut();
	$selenium->signUp($name2, $password2, $email2);	
	$selenium->signIn($name2, $password2);
	$selenium->write('verifyValue', 'testing_count', $count + 7);
	$selenium->openPage('/' . $name);			
	$selenium->write('clickAndWait', 'follow');	
	$selenium->signOut();
	$selenium->signUp($name3, $password3, $email3);	
	$selenium->signIn($name3, $password3);
	$selenium->write('verifyValue', 'testing_count', $count + 10);	
	$selenium->openPage('/' . $name);			
	$selenium->write('clickAndWait', 'follow');		
	$selenium->signOut();
	$selenium->signIn($name, $password);
	$selenium->makeGroup($group);
	$selenium->write('verifyValue', 'testing_count', $count + 15);		
	$selenium->makeGroup($group2);
	$selenium->makeGroup($group3);	
	$selenium->subscribeToGroup($group, $name, $password, $name2, $password2, $email2);
	$selenium->subscribeToGroup($group2, $name, $password, $name2, $password2, $email2);
	$selenium->subscribeToGroup($group3, $name, $password, $name2, $password2, $email2);
	$selenium->subscribeToGroup($group, $name, $password, $name3, $password3, $email3);
	$selenium->subscribeToGroup($group2, $name, $password, $name3, $password3, $email3);	
	$selenium->signOut();
	$selenium->signIn($name, $password);	
	$selenium->openPage('/inbox');
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup/option', $name3);	
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup/option[2]', $name2);	
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup[2]/option', '!' . $group);
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup[2]/option[2]', '!' . $group2);
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup[2]/option[3]', '!' . $group3);
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup[3]/option', $name3);
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup[3]/option[2]', $name2);
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup[4]/option', $name3);
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup[4]/option[2]', $name2);
	$selenium->write('verifyValue', 'xpath=//select[@id=\'to\']/optgroup[5]/option', $name2);		
	$selenium->openPage('/admin/flush');
?>